In [1]:
import pandas as pd
import numpy as np 
animals = pd.read_csv('animals.csv')

In [4]:
# animals.head(4)
animals['body10'] = animals['bodywt']+10
animals['body+brain'] = animals['bodywt']+animals['brainwt']
animals.head(4)

   brainwt   bodywt      animal   body10  body+brain
0    3.385   44.500  Arctic_fox   54.500      47.885
1    0.480   15.499  Owl_monkey   25.499      15.979
2    1.350    8.100      Beaver   18.100       9.450
3  464.983  423.012         Cow  433.012     887.995

In [11]:
animals['brainwt']

0        3.385
1        0.480
2        1.350
3      464.983
4       36.328
5       27.660
6       14.831
7        1.040
8        4.190
9        0.425
10       0.101
11       0.920
12       1.000
13       0.005
14       0.060
15       3.500
16       2.000
17       1.700
18    2547.070
19       0.023
20     187.092
21     521.026
22       0.785
23      10.000
24       3.300
25       0.200
26       1.410
27     529.006
28     206.996
29      85.004
        ...
32    6654.180
33       3.500
34       6.800
35      34.998
36       4.050
37       0.120
38       0.023
39       0.010
40       1.400
41     250.010
42       2.500
43      55.501
44     100.003
45      52.159
46      10.550
47       0.550
48      59.997
49       3.600
50       4.288
51       0.280
52       0.075
53       0.122
54       0.048
55     192.001
56       3.000
57     160.004
58       0.900
59       1.620
60       0.104
61       4.235
Name: brainwt, Length: 62, dtype: float64

In [5]:
animals['wtratio'] = animals['bodywt'] / animals['brainwt']

In [6]:
animals.head(4)

   brainwt   bodywt      animal   body10  body+brain    wtratio
0    3.385   44.500  Arctic_fox   54.500      47.885  13.146233
1    0.480   15.499  Owl_monkey   25.499      15.979  32.289583
2    1.350    8.100      Beaver   18.100       9.450   6.000000
3  464.983  423.012         Cow  433.012     887.995   0.909736

In [7]:
animals['wtratiozerocheck'] = np.where(animals['brainwt'] != 0, animals['bodywt'] / animals['brainwt'], 0)

In [8]:
animals.head(10)

,brainwt,bodywt,animal,body10,body+brain,wtratio,wtratiozerocheck
0,3.385,44.500,Arctic_fox,54.500,47.885,13.146233,13.146233
1,0.480,15.499,Owl_monkey,25.499,15.979,32.289583,32.289583
2,1.350,8.100,Beaver,18.100,9.450,6.000000,6.000000
3,464.983,423.012,Cow,433.012,887.995,0.909736,0.909736
4,36.328,119.498,Gray_wolf,129.498,155.826,3.289419,3.289419
5,27.660,114.996,Goat,124.996,142.656,4.157484,4.157484
6,14.831,98.199,Roe_deer,108.199,113.030,6.621199,6.621199
7,1.040,5.500,Guinea_pig,15.500,6.540,5.288462,5.288462
8,4.190,57.998,Vervet,67.998,62.188,13.842005,13.842005
9,0.425,6.400,Chinchilla,16.400,6.825,15.058824,15.058824

In [12]:
animals.sum(axis=1)[0]

176.5624667651403

In [13]:
import numpy as np
import pandas as pd

vehicles = pd.read_csv('vehicles.csv')

In [14]:
vehicles.head(10)

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
5,Acura,2.2CL/3.0CL,1997,2.2,4.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,14.982273,20,26,22,403.954545,1500
6,Acura,2.2CL/3.0CL,1997,2.2,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.733750,22,28,24,370.291667,1400
7,Acura,2.2CL/3.0CL,1997,3.0,6.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,16.480500,18,26,20,444.350000,1650
8,Acura,2.3CL/3.0CL,1998,2.3,4.0,Automatic 4-spd,Front-Wheel Drive,Subcompact Cars,Regular,14.982273,19,27,22,403.954545,1500
9,Acura,2.3CL/3.0CL,1998,2.3,4.0,Manual 5-spd,Front-Wheel Drive,Subcompact Cars,Regular,13.733750,21,29,24,370.291667,1400

In [20]:
vehicles.groupby(['Transmission'])['Highway MPG', 'City MPG', 'Combined MPG'].mean()

                                  Highway MPG   City MPG  Combined MPG
Transmission
Auto (AV)                           40.000000  35.000000     37.000000
Auto (AV-S6)                        25.000000  22.000000     23.000000
Auto (AV-S8)                        22.000000  20.000000     21.000000
Auto(A1)                            37.000000  41.000000     39.000000
Auto(AM-S6)                         32.978261  24.315217     27.554348
Auto(AM-S7)                         25.300781  17.746094     20.425781
Auto(AM-S8)                         32.000000  23.666667     26.666667
Auto(AM-S9)                         22.000000  21.000000     21.000000
Auto(AM5)                           39.000000  33.666667     36.000000
Auto(AM6)                           31.345455  23.909091     26.736364
Auto(AM7)                           22.382166  16.248408     18.420382
Auto(AM8)                           28.600000  22.400000     24.600000
Auto(AV-S6)                         30.800000  25.944828     27.848276
Auto(AV-S7)                         33.746032  27.952381     30.206349
Auto(AV-S8)                         28.538462  22.846154     24.961538
Auto(L3)                            17.000000  14.000000     15.500000
Auto(L4)                            19.000000  13.500000     15.500000
Automatic (A1)                      31.666667  34.000000     32.666667
Automatic (A6)                      21.000000  14.000000     16.500000
Automatic (AM5)                     41.000000  33.000000     36.000000
Automatic (AM6)                     18.000000  13.000000     15.000000
Automatic (AV)                      30.000000  21.750000     24.750000
Automatic (AV-S6)                   27.777778  23.666667     25.222222
Automatic (S4)                      24.768559  18.074236     20.528384
Automatic (S5)                      24.205596  17.087591     19.698297
Automatic (S6)                      25.938807  18.337514     21.096921
Automatic (S7)                      23.605364  16.804598     19.195402
Automatic (S8)                      26.983333  18.450000     21.500000
Automatic (S9)                      28.307692  19.923077     23.038462
Automatic (variable gear ratios)    31.094815  27.460741     28.777778
Automatic 3-spd                     21.630343  17.449750     19.033500
Automatic 4-spd                     21.691639  15.944261     18.042607
Automatic 5-spd                     21.647167  15.445417     17.693229
Automatic 6-spd                     23.768156  16.720670     19.237430
Automatic 6spd                      34.000000  21.000000     26.000000
Automatic 7-spd                     24.413897  17.117825     19.746224
Automatic 8-spd                     24.448560  16.576132     19.279835
Automatic 9-spd                     28.366667  20.077778     23.200000
Manual 3-spd                        16.945946  14.229730     15.256757
Manual 4-spd                        21.042113  16.871363     18.462481
Manual 5 spd                        14.000000  14.000000     14.000000
Manual 5-spd                        25.664312  19.242327     21.634391
Manual 6-spd                        26.202229  18.306232     21.153941
Manual 7-spd                        26.205882  18.220588     21.117647
Manual(M7)                          22.333333  14.000000     17.000000

In [16]:
vehicles.groupby(['Fuel Type', 'Cylinders','Drivetrain'])['CO2 Emission Grams/Mile'].median()

Fuel Type                    Cylinders  Drivetrain
CNG                          4.0        Front-Wheel Drive             253.197321
                             6.0        Front-Wheel Drive             417.030882
                             8.0        4-Wheel or All-Wheel Drive    787.725000
                                        Rear-Wheel Drive              545.348077
Diesel                       4.0        2-Wheel Drive                 363.571429
                                        4-Wheel Drive                 367.000000
                                        4-Wheel or All-Wheel Drive    415.683333
                                        All-Wheel Drive               299.000000
                                        Front-Wheel Drive             299.411765
                                        Rear-Wheel Drive              377.037037
                             5.0        Rear-Wheel Drive              391.538462
                             6.0        4-Wheel Drive                 460.863636
                                        4-Wheel or All-Wheel Drive    509.000000
                                        All-Wheel Drive               442.000000
                                        Front-Wheel Drive             391.538462
                                        Rear-Wheel Drive              424.166667
                             8.0        2-Wheel Drive                 535.789474
                                        4-Wheel or All-Wheel Drive    636.250000
                                        Front-Wheel Drive             496.880952
                                        Rear-Wheel Drive              565.555556
                             10.0       4-Wheel or All-Wheel Drive    598.823529
Gasoline or E85              4.0        All-Wheel Drive               379.000000
                                        Front-Wheel Drive             355.480000
                                        Rear-Wheel Drive              435.845694
                             6.0        4-Wheel Drive                 475.000000
                                        4-Wheel or All-Wheel Drive    592.466667
                                        All-Wheel Drive               444.350000
                                        Front-Wheel Drive             423.190476
                                        Part-time 4-Wheel Drive       499.861111
                                        Rear-Wheel Drive              467.736842
                                                                         ...
Regular                      4.0        2-Wheel Drive                 423.190476
                                        4-Wheel Drive                 398.000000
                                        4-Wheel or All-Wheel Drive    423.190476
                                        All-Wheel Drive               366.000000
                                        Front-Wheel Drive             355.480000
                                        Part-time 4-Wheel Drive       460.000000
                                        Rear-Wheel Drive              444.350000
                             5.0        4-Wheel Drive                 493.722222
                                        4-Wheel or All-Wheel Drive    493.722222
                                        All-Wheel Drive               383.000000
                                        Front-Wheel Drive             403.954545
                                        Rear-Wheel Drive              493.722222
                             6.0        2-Wheel Drive                 592.466667
                                        4-Wheel Drive                 503.000000
                                        4-Wheel or All-Wheel Drive    555.437500
                                        All-Wheel Drive               446.000000
                                        Front-Wheel Drive             444.350000
                                        Part-time 4-Wheel Drive       499.000000
                                        Rear-Wheel Drive              522.764706
                             8.0        2-Wheel Drive                 683.615385
                                        4-Wheel Drive                 531.000000
                                        4-Wheel or All-Wheel Drive    683.615385
                                        All-Wheel Drive               493.722222
                                        Front-Wheel Drive             493.722222
                                        Part-time 4-Wheel Drive       606.000000
                                        Rear-Wheel Drive              634.785714
                             10.0       Rear-Wheel Drive              776.500000
                             12.0       Rear-Wheel Drive              683.615385
Regular Gas and Electricity  4.0        Front-Wheel Drive             129.000000
Regular Gas or Electricity   4.0        Front-Wheel Drive              51.000000
Name: CO2 Emission Grams/Mile, Length: 135, dtype: float64

In [18]:
vehicles.groupby(['Fuel Type','Cylinders']).agg({'Combined MPG':['mean', 'median', 'std']})

                                      Combined MPG
                                              mean median       std
Fuel Type                   Cylinders
CNG                         4.0          27.619048   28.0  2.578298
                            6.0          17.000000   17.0  0.000000
                            8.0          12.694444   12.5  2.214491
Diesel                      4.0          31.468553   33.0  4.574372
                            5.0          24.470588   26.0  3.572773
                            6.0          23.754967   23.0  3.015442
                            8.0          17.384798   17.0  1.519448
                            10.0         17.250000   17.0  0.500000
Gasoline or E85             4.0          25.062992   25.0  3.020428
                            6.0          19.763231   20.0  1.906234
                            8.0          15.121298   15.0  1.632807
Gasoline or natural gas     4.0          23.200000   23.0  0.836660
                            6.0          20.000000   20.0  0.000000
                            8.0          11.615385   12.0  0.767948
Gasoline or propane         8.0          13.500000   13.5  1.603567
Midgrade                    6.0          22.000000   21.0  1.414214
                            8.0          17.043478   17.0  1.365917
Premium                     2.0          18.272727   18.0  0.455842
                            3.0          34.961538   36.0  1.684773
                            4.0          23.325777   23.0  3.620906
                            5.0          20.463087   20.0  1.297620
                            6.0          19.808354   20.0  2.388879
                            8.0          16.255311   17.0  2.411833
                            10.0         13.985816   14.0  1.760624
                            12.0         12.988119   13.0  1.764919
                            16.0         10.000000   10.0  0.000000
Premium Gas or Electricity  2.0          39.000000   39.0  0.000000
                            4.0          33.300000   35.0  5.355164
                            6.0          22.000000   22.0  0.000000
                            8.0          22.000000   22.0       NaN
Premium and Electricity     3.0          28.000000   28.0  0.000000
                            4.0          28.888889   27.0  5.325515
                            6.0          24.666667   25.0  1.861899
                            8.0          17.000000   17.0  0.000000
Premium or E85              4.0          24.392857   24.0  1.370031
                            6.0          21.018182   21.0  1.509119
                            8.0          17.312500   18.0  1.078193
                            12.0         14.318182   14.0  0.646335
Regular                     2.0          17.304348   17.0  0.470472
                            3.0          36.965116   36.0  6.081220
                            4.0          23.959436   23.0  4.363611
                            5.0          20.068627   19.0  3.033020
                            6.0          17.860770   18.0  2.357853
                            8.0          14.337204   14.0  2.305063
                            10.0         11.500000   11.5  0.534522
                            12.0         12.571429   13.0  1.092372
Regular Gas and Electricity 4.0          41.937500   38.5  5.246824
Regular Gas or Electricity  4.0          42.000000   42.0  0.000000

In [19]:
vehicles.groupby(['Fuel Type','Cylinders'])['Combined MPG'].agg(['mean', 'median', 'std'])

                                            mean  median       std
Fuel Type                   Cylinders
CNG                         4.0        27.619048    28.0  2.578298
                            6.0        17.000000    17.0  0.000000
                            8.0        12.694444    12.5  2.214491
Diesel                      4.0        31.468553    33.0  4.574372
                            5.0        24.470588    26.0  3.572773
                            6.0        23.754967    23.0  3.015442
                            8.0        17.384798    17.0  1.519448
                            10.0       17.250000    17.0  0.500000
Gasoline or E85             4.0        25.062992    25.0  3.020428
                            6.0        19.763231    20.0  1.906234
                            8.0        15.121298    15.0  1.632807
Gasoline or natural gas     4.0        23.200000    23.0  0.836660
                            6.0        20.000000    20.0  0.000000
                            8.0        11.615385    12.0  0.767948
Gasoline or propane         8.0        13.500000    13.5  1.603567
Midgrade                    6.0        22.000000    21.0  1.414214
                            8.0        17.043478    17.0  1.365917
Premium                     2.0        18.272727    18.0  0.455842
                            3.0        34.961538    36.0  1.684773
                            4.0        23.325777    23.0  3.620906
                            5.0        20.463087    20.0  1.297620
                            6.0        19.808354    20.0  2.388879
                            8.0        16.255311    17.0  2.411833
                            10.0       13.985816    14.0  1.760624
                            12.0       12.988119    13.0  1.764919
                            16.0       10.000000    10.0  0.000000
Premium Gas or Electricity  2.0        39.000000    39.0  0.000000
                            4.0        33.300000    35.0  5.355164
                            6.0        22.000000    22.0  0.000000
                            8.0        22.000000    22.0       NaN
Premium and Electricity     3.0        28.000000    28.0  0.000000
                            4.0        28.888889    27.0  5.325515
                            6.0        24.666667    25.0  1.861899
                            8.0        17.000000    17.0  0.000000
Premium or E85              4.0        24.392857    24.0  1.370031
                            6.0        21.018182    21.0  1.509119
                            8.0        17.312500    18.0  1.078193
                            12.0       14.318182    14.0  0.646335
Regular                     2.0        17.304348    17.0  0.470472
                            3.0        36.965116    36.0  6.081220
                            4.0        23.959436    23.0  4.363611
                            5.0        20.068627    19.0  3.033020
                            6.0        17.860770    18.0  2.357853
                            8.0        14.337204    14.0  2.305063
                            10.0       11.500000    11.5  0.534522
                            12.0       12.571429    13.0  1.092372
Regular Gas and Electricity 4.0        41.937500    38.5  5.246824
Regular Gas or Electricity  4.0        42.000000    42.0  0.000000

In [24]:
vehicles.groupby(['Fuel Type']).agg({'Combined MPG':['mean', 'median', 'std']})

                            Combined MPG
                                    mean median       std
Fuel Type
CNG                            18.133333   14.5  7.436663
Diesel                         23.488474   21.0  7.054702
Gasoline or E85                17.572385   17.0  3.822538
Gasoline or natural gas        15.350000   12.0  5.343712
Gasoline or propane            13.500000   13.5  1.603567
Midgrade                       17.378378   17.0  1.848381
Premium                        19.343816   19.0  4.097972
Premium Gas or Electricity     31.647059   33.0  7.158397
Premium and Electricity        26.300000   25.5  5.141165
Premium or E85                 20.090909   20.0  3.676502
Regular                        20.144698   20.0  5.317500
Regular Gas and Electricity    41.937500   38.5  5.246824
Regular Gas or Electricity     42.000000   42.0  0.000000

In [21]:
from scipy import stats

def agg_mode(x):
    return(stats.mode(x)[0])

In [24]:
stats.mode(vehicles['Vehicle Class'])[0][0]

'Compact Cars'

In [6]:
vehicles.groupby("Transmission")["Vehicle Class"].agg(agg_mode)

/anaconda3/lib/python3.7/site-packages/scipy/stats/stats.py:248: RuntimeWarning: The input array could not be properly checked for nan values. nan values will be ignored.
  "values. nan values will be ignored.", RuntimeWarning)

Transmission
Auto (AV)                                                 Compact Cars
Auto (AV-S6)                                              Compact Cars
Auto (AV-S8)                                              Midsize Cars
Auto(A1)                                               Subcompact Cars
Auto(AM-S6)                                               Compact Cars
Auto(AM-S7)                                           Minicompact Cars
Auto(AM-S8)                                               Compact Cars
Auto(AM-S9)                                                Two Seaters
Auto(AM5)                                                  Two Seaters
Auto(AM6)                                                 Compact Cars
Auto(AM7)                                                  Two Seaters
Auto(AM8)                           Standard Sport Utility Vehicle 4WD
Auto(AV-S6)                                               Midsize Cars
Auto(AV-S7)                                               Midsize Cars
Auto(AV-S8)                                               Midsize Cars
Auto(L3)                                      Special Purpose Vehicles
Auto(L4)                                      Special Purpose Vehicles
Automatic (A1)                                         Subcompact Cars
Automatic (A6)                                            Compact Cars
Automatic (AM5)                                            Two Seaters
Automatic (AM6)                                            Two Seaters
Automatic (AV)                                            Midsize Cars
Automatic (AV-S6)                                         Compact Cars
Automatic (S4)                                            Compact Cars
Automatic (S5)                                            Compact Cars
Automatic (S6)                                            Midsize Cars
Automatic (S7)                                            Midsize Cars
Automatic (S8)                                            Midsize Cars
Automatic (S9)                         Small Sport Utility Vehicle 4WD
Automatic (variable gear ratios)                          Midsize Cars
Automatic 3-spd                                           Compact Cars
Automatic 4-spd                                           Midsize Cars
Automatic 5-spd                            Sport Utility Vehicle - 4WD
Automatic 6-spd                            Sport Utility Vehicle - 2WD
Automatic 6spd                                            Midsize Cars
Automatic 7-spd                                           Compact Cars
Automatic 8-spd                                             Large Cars
Automatic 9-spd                        Small Sport Utility Vehicle 4WD
Manual 3-spd                                                      Vans
Manual 4-spd                                    Standard Pickup Trucks
Manual 5 spd                                                      Vans
Manual 5-spd                                              Compact Cars
Manual 6-spd                                              Compact Cars
Manual 7-spd                                          Minicompact Cars
Manual(M7)                                                 Two Seaters
Name: Vehicle Class, dtype: object